export const CATEGORY_WORDS = {
    'Movies': [
        { word: 'Baahubali', hint: 'The query about Why Kattappa killed him' },
        { word: 'Vikram', hint: 'A ghost returns to settle a vintage score' },
        { word: 'Ponniyin Selvan', hint: 'Splendor of the Chola winds' },
        { word: 'Jai Bhim', hint: 'When law fights for the voiceless' },
        { word: 'Master', hint: 'A clash of addiction and influence' },
        { word: 'Pushpa', hint: 'The rise of red timber and fire' },
        { word: 'Enthiran', hint: 'A creation that learned to love and destroy' },
        { word: 'Sivaji', hint: 'Cleaning the system with hidden wealth' },
        { word: 'Vada Chennai', hint: 'A game of carrom and blood in the north' },
        { word: 'Asuran', hint: 'A peaceful father forced to show his old rage' },
        { word: 'Karnan', hint: 'A horse and a sword for the village rights' },
        { word: 'Soorarai Pottru', hint: 'Selling dreams at a single rupee' },
        { word: '96', hint: 'Two lovers, one night, and a high school memory' },
        { word: 'Kaithi', hint: 'A prisoner, a truck, and a night of survival' },
        { word: 'Thani Oruvan', hint: 'Polishing your enemy to make yourself better' },
        { word: 'Anniyan', hint: 'Garuda Puranam and multiple masks' },
        { word: 'Thupakki', hint: 'A soldier on leave playing a game of numbers' },
        { word: 'Kaththi', hint: 'A slider between a petty thief and a social hero' },
        { word: 'Mersal', hint: 'Three faces of a medical miracle' },
        { word: 'Sarkar', hint: 'Voting for your own finger and the throne' },
        { word: 'Petta', hint: 'The swagger of a hostel warden with a past' },
        { word: 'Kabali', hint: 'A suit-wearing lion of the Malaysian streets' },
        { word: 'Ghajini', hint: 'Reminders written on the skin' },
        { word: 'Ayan', hint: 'The art of carrying what should not be found' },
        { word: 'Mankatha', hint: 'A coin toss and a game of high-stakes bet' },
        { word: 'Theri', hint: 'A bakery owner with a lethal past' },
        { word: 'Singam', hint: 'A roar from the dusty roads of Nallur' },
        { word: 'VTV', hint: 'A filmmaker chasing a girl in Kerala and beyond' },
        { word: 'Raja Rani', hint: 'Two broken hearts finding a new rhythm' },
        { word: 'Saamy', hint: 'A cop who loves spicy curd rice and justice' },
        { word: 'Ghilli', hint: 'Kabaddi in Madurai, rescue in Chennai' },
        { word: 'Run', hint: 'A high-speed chase through the city streets' },
        { word: 'Kadhalan', hint: 'Invisible dance and a political heartbeat' },
        { word: 'Gentleman', hint: 'A master of disguises and a home for others' },
        { word: 'Roja', hint: 'A cry for peace among the snow-capped peaks' },
        { word: 'Bombay', hint: 'A union tested by the flames of separation' },
        { word: 'Alaipayuthey', hint: 'A wedding on a train and a hospital wait' },
        { word: 'Ok Kanmani', hint: 'Living together without the strings attached' },
        { word: 'Sarpatta', hint: 'Winning the belt with your fists in the ring' },
        { word: 'Doctor', hint: 'A cold-blooded physician against the shadows' },
        { word: 'Beast', hint: 'A spy trapped in a concrete shopping cage' },
        { word: 'Varisu', hint: 'The third son returning to fix the empire' },
        { word: 'Thunivu', hint: 'A dark dance inside the vault of a bank' },
        { word: 'Leo', hint: 'A chocolate maker or a bloodthirsty kingpin?' },
        { word: 'Jailer', hint: 'A tiger who stays in his cage until poked' },
        { word: 'Maanaadu', hint: 'The same day, the same airport, the same bullet' },
        { word: 'Iruvar', hint: 'The poetry of politics and silver screen rivals' },
        { word: 'Nayagan', hint: 'If a good man says its okay, it is okay' },
        { word: 'Mouna Ragam', hint: 'A gift of anklets and a silent heart' },
        { word: 'Pithamagan', hint: 'A man who knows the dead better than the living' }
    ],
    'Celebrities': [
        { word: 'Rajinikanth', hint: 'The man of style and the walk of thunder' },
        { word: 'Vijay', hint: 'The leader of the millions who dance to his beat' },
        { word: 'Ajith', hint: 'The racer who never uses a stunt double' },
        { word: 'Kamal Haasan', hint: 'The encyclopedia of the various cinematic arts' },
        { word: 'Suriya', hint: 'The actor who gives his literal sweat and blood' },
        { word: 'Nayanthara', hint: 'The sovereign who rules the emerald screens' },
        { word: 'AR Rahman', hint: 'The man who turned divine silence into global sound' },
        { word: 'Anirudh', hint: 'The digital age maestro of the high-energy mass' },
        { word: 'Dhanush', hint: 'A lean figure with a world-class acting range' },
        { word: 'Vikram', hint: 'The chameleon who lives in a different skin' },
        { word: 'Sivakarthikeyan', hint: 'A voice from the screen that became a giant' },
        { word: 'Vijay Sethupathi', hint: 'The man who stays real amidst the make-believe' },
        { word: 'Trisha', hint: 'The name that defined romance for two decades' },
        { word: 'Samantha', hint: 'A star that shines across the Deccan plateaus' },
        { word: 'Karthi', hint: 'A mix of raw intensity and boy-next-door charm' },
        { word: 'Yuvan Shankar Raja', hint: 'The dealer of the melancholic soul melodies' },
        { word: 'Harris Jayaraj', hint: 'The architect of the humming bridge' },
        { word: 'GV Prakash', hint: 'The youth icon behind the booth and the lens' },
        { word: 'Vetrimaaran', hint: 'The observer of the raw and the political' },
        { word: 'Lokesh Kanagaraj', hint: 'Connecting the dots of a dark universe' },
        { word: 'Nelson', hint: 'Finding a laugh in the darkest of corners' },
        { word: 'Atlee', hint: 'The king of the grand commercial vision' },
        { word: 'Maniratnam', hint: 'Master of frames, lights, and silhouettes' },
        { word: 'Amitabh Bachchan', hint: 'The deep voice that echoed through an era' },
        { word: 'Shah Rukh Khan', hint: 'The arms spread wide on the global stage' },
        { word: 'Salman Khan', hint: 'The big brother of the silver screen' },
        { word: 'Deepika Padukone', hint: 'The graceful face of the modern epic' },
        { word: 'Sachin Tendulkar', hint: 'The master who carried the hopes of a billion' },
        { word: 'Virat Kohli', hint: 'The aggression and the fire on the green field' },
        { word: 'MS Dhoni', hint: 'The silence behind the stumps and the finish' },
        { word: 'Cristiano Ronaldo', hint: 'A machine of perfection and sheer hard work' },
        { word: 'Lionel Messi', hint: 'Magic woven with the left foot' },
        { word: 'Tom Cruise', hint: 'The man who fights gravity for real' },
        { word: 'The Rock', hint: 'The people\'s champion with a hard exterior' },
        { word: 'Jackie Chan', hint: 'Fights with a chair and a laugh' },
        { word: 'Brad Pitt', hint: 'The face that defines a Hollywood legend' },
        { word: 'Angelina Jolie', hint: 'The fierce beauty of the action and the charity' },
        { word: 'Leonardo DiCaprio', hint: 'Finally caught the gold after many lives' },
        { word: 'Keanu Reeves', hint: 'The kind man with a dog and a dark past' },
        { word: 'Robert Downey Jr', hint: 'The metal genius who built a legacy' },
        { word: 'Vadivelu', hint: 'The mirror to every common man\'s struggle' },
        { word: 'Santhanam', hint: 'The quick-witted master of the counter-punch' },
        { word: 'Yogi Babu', hint: 'The curly-haired laugh in every frame' },
        { word: 'Prakash Raj', hint: 'A different tone for every role he holds' },
        { word: 'Nasser', hint: 'The veteran who can be anyone he wants' },
        { word: 'Sridevi', hint: 'The eyes that spoke more than the scripts' },
        { word: 'Keerthy Suresh', hint: 'Channeling a legend for her own gold' },
        { word: 'Mohanlal', hint: 'The absolute natural of the southern breeze' },
        { word: 'Mammootty', hint: 'The aging legend who only gets sharper' },
        { word: 'S.S. Rajamouli', hint: 'The visionary who made the world look at us' }
    ],
    'Sports': [
        { word: 'Cricket', hint: 'A willow, a leather ball, and 22 yards' },
        { word: 'Football', hint: 'A fever that lasts 90 minutes and a globe' },
        { word: 'Kabaddi', hint: 'Holding your breath and crossing the line' },
        { word: 'Chess', hint: 'A silent war on a checkered board' },
        { word: 'Tennis', hint: 'A duel across a net with a yellow ball' },
        { word: 'Badminton', hint: 'A fight over a bird with feathers' },
        { word: 'Hockey', hint: 'Sticks and a sphere on a green turf' },
        { word: 'Basketball', hint: 'Flying high to reach the orange hoop' },
        { word: 'Volleyball', hint: 'Keep it in the air with a Spike' },
        { word: 'Baseball', hint: 'Three strikes and you\'re out in the diamond' },
        { word: 'Table Tennis', hint: 'Rapid fire on a small wooden table' },
        { word: 'Golf', hint: 'A long walk to a very tiny hole' },
        { word: 'Boxing', hint: 'The sweet science of the ring' },
        { word: 'Wrestling', hint: 'Pinning down the opponent on the mat' },
        { word: 'Swimming', hint: 'Cutting through the blue with a stroke' },
        { word: 'Athletics', hint: 'The fastest, the highest, the strongest' },
        { word: 'Archery', hint: 'Focus on the yellow circle in the middle' },
        { word: 'Shooting', hint: 'Pulling the trigger with a steady breath' },
        { word: 'Billiards', hint: 'A green table and three smooth spheres' },
        { word: 'Formula 1', hint: 'Chasing the checkered flag at 300km/h' },
        { word: 'MotoGP', hint: 'Leaning low on two wheels' },
        { word: 'Rugby', hint: 'A battle for an oval ball in a scrum' },
        { word: 'Gymnastics', hint: 'The art of the perfect landing' },
        { word: 'Weightlifting', hint: 'A test of the spine and the spirit' },
        { word: 'Cycling', hint: 'Two wheels and a yellow jersey dream' },
        { word: 'Rowing', hint: 'Backward motion to move forward fast' },
        { word: 'Surfing', hint: 'Dancing on the edge of a blue wave' },
        { word: 'Skateboarding', hint: 'Asphalt surfing with a kickflip' },
        { word: 'Karate', hint: 'The empty hand path' },
        { word: 'Judo', hint: 'Using the opponent\'s weight against them' },
        { word: 'Fencing', hint: 'A dance of the foils and the masks' },
        { word: 'Squash', hint: 'Trapped in a room with a rubber ball' },
        { word: 'Snooker', hint: 'A long cue and 21 varied points' },
        { word: 'Bowling', hint: 'Ten pins waiting for a heavy roll' },
        { word: 'Darts', hint: 'Aiming for the triple-twenty' },
        { word: 'Ice Hockey', hint: 'Blade shoes and a frozen arena' },
        { word: 'Skiing', hint: 'Sliding down the white slopes' },
        { word: 'Snowboarding', hint: 'One board, one mountain, much snow' },
        { word: 'Curling', hint: 'Sweeping the path for a sliding stone' },
        { word: 'Equestrian', hint: 'The bond between a rider and a beast' },
        { word: 'Polo', hint: 'Swinging a mallet from a heights' },
        { word: 'Triathlon', hint: 'The ultimate test of swim, bike, and run' },
        { word: 'Taekwondo', hint: 'The way of the foot and the fist' },
        { word: 'Marathon', hint: 'The 26.2 mile journey of host' },
        { word: 'Pole Vault', hint: 'Using a stick to touch the sky' },
        { word: 'Shot Put', hint: 'Throwing a heavy iron world' },
        { word: 'High Jump', hint: 'Going over the bar without a touch' },
        { word: 'Softball', hint: 'A larger ball and a faster pitch' },
        { word: 'Carrom', hint: 'Flick of the finger on a wooden board' },
        { word: 'Kho Kho', hint: 'Sit, stand, and chase in a line' }
    ],
    'Animals': [
        { word: 'Lion', hint: 'A prideful ruler with a golden mane' },
        { word: 'Tiger', hint: 'The phantom of the jungle with stripes' },
        { word: 'Elephant', hint: 'A memory that never fades with a trunk' },
        { word: 'Giraffe', hint: 'Looking down from the clouds of the savannah' },
        { word: 'Zebra', hint: 'A barcode on the run' },
        { word: 'Kangaroo', hint: 'A pocket for the young and a powerful kick' },
        { word: 'Panda', hint: 'A black and white eater of bamboo' },
        { word: 'Penguin', hint: 'Dressing in a tuxedo for the ice' },
        { word: 'Dolphin', hint: 'The smiling acrobat of the waves' },
        { word: 'Whale', hint: 'A giant song under the deep blue' },
        { word: 'Shark', hint: 'A fin that causes silence on the shore' },
        { word: 'Octopus', hint: 'Eight arms and a cloud of ink' },
        { word: 'Turtle', hint: 'Carrying a house through the ocean' },
        { word: 'Gorilla', hint: 'A gentle giant of the mountain mist' },
        { word: 'Chimpanzee', hint: 'A mirror of ourselves in the trees' },
        { word: 'Leopard', hint: 'Spotted silence in the night' },
        { word: 'Cheetah', hint: 'The blur in the grass' },
        { word: 'Rhino', hint: 'A tank with a nasal weapon' },
        { word: 'Hippo', hint: 'The river guardian with a wide yawn' },
        { word: 'Crocodile', hint: 'A living log in the swamp' },
        { word: 'Snake', hint: 'A rope that bites' },
        { word: 'Eagle', hint: 'The king of the high thermals' },
        { word: 'Parrot', hint: 'The colorful echo of the forest' },
        { word: 'Peacock', hint: 'The thousand-eyed dancer' },
        { word: 'Owl', hint: 'The silent hunter with the wide eyes' },
        { word: 'Wolf', hint: 'The lonely howl in the pack' },
        { word: 'Fox', hint: 'A tail of fire and a clever mask' },
        { word: 'Bear', hint: 'The sleeper in the cave of winter' },
        { word: 'Deer', hint: 'A graceful crown in the forest' },
        { word: 'Rabbit', hint: 'A burrower with long twitching ears' },
        { word: 'Horse', hint: 'The wind on four legs' },
        { word: 'Cow', hint: 'The sacred mother of the fields' },
        { word: 'Goat', hint: 'Climbing the mountains with a bleat' },
        { word: 'Sheep', hint: 'A cloud of wool on the hillside' },
        { word: 'Dog', hint: 'The loyalty that waits by the door' },
        { word: 'Cat', hint: 'The independent king of the house' },
        { word: 'Camel', hint: 'A hump for the desert journey' },
        { word: 'Squirrel', hint: 'A bushy-tailed gatherer of nuts' },
        { word: 'Bat', hint: 'Seeing with sound in the dark' },
        { word: 'Monkey', hint: 'The prankster of the jungle branches' },
        { word: 'Polar Bear', hint: 'The white giant of the melting ice' },
        { word: 'Butterfly', hint: 'A transformation on painted wings' },
        { word: 'Bee', hint: 'The worker in the golden hive' },
        { word: 'Ant', hint: 'A tiny architect of the underground' },
        { word: 'Frog', hint: 'A leap from the lily pad' },
        { word: 'Crab', hint: 'Walking sideways on the sand' },
        { word: 'Spider', hint: 'The weaver of the sticky trap' },
        { word: 'Koala', hint: 'A sleepy climber with grey fur' },
        { word: 'Sloth', hint: 'Life in the slowest lane' },
        { word: 'Ostrich', hint: 'A runner that cannot fly' }
    ],
    'Food': [
        { word: 'Biryani', hint: 'Layers of spice and long-grain dreams' },
        { word: 'Dosa', hint: 'A golden moon on a hot plate' },
        { word: 'Idli', hint: 'A soft white cloud for breakfast' },
        { word: 'Samosa', hint: 'A triangular secret of potato and peas' },
        { word: 'Pizza', hint: 'A round canvas of cheese and dough' },
        { word: 'Burger', hint: 'A tower of meat and bun' },
        { word: 'Sushi', hint: 'Sea gift wrapped in rice and vine' },
        { word: 'Pasta', hint: 'The doughy heart of the Italian kitchen' },
        { word: 'Tacos', hint: 'A crunchy fold of the Mexican sun' },
        { word: 'Ramen', hint: 'Noodles in a bowl of soul search' },
        { word: 'Steak', hint: 'The prime choice of the grill' },
        { word: 'Fried Chicken', hint: 'The golden crunch of the batter' },
        { word: 'Waffles', hint: 'A grid of syrup and butter' },
        { word: 'Pancakes', hint: 'A stack of soft morning discs' },
        { word: 'Omelette', hint: 'Eggs folded with a golden touch' },
        { word: 'Paratha', hint: 'The layered flatbread of the north' },
        { word: 'Naan', hint: 'Baked on the walls of the clay oven' },
        { word: 'Paneer Tikka', hint: 'Grilled cubes of the white block' },
        { word: 'Butter Chicken', hint: 'A silk of tomato and cream' },
        { word: 'Pongal', hint: 'A harvest blend of rice and pepper' },
        { word: 'Vada Pav', hint: 'The pulse of the Mumbai streets' },
        { word: 'Pani Puri', hint: 'A burst of spicy water in a shell' },
        { word: 'Ice Cream', hint: 'A Sweet melt on a summer day' },
        { word: 'Cake', hint: 'The center of every celebration' },
        { word: 'Chocolate', hint: 'The dark love that melts in the hand' },
        { word: 'Apple Pie', hint: 'A nostalgic crust of the orchard' },
        { word: 'Coffee', hint: 'A bitter bean that awakens the mind' },
        { word: 'Tea', hint: 'The leaf that traveled across the empires' },
        { word: 'Milkshake', hint: 'The thick blend of dairy and dream' },
        { word: 'Salad', hint: 'A garden in a bowl' },
        { word: 'Sandwich', hint: 'What lies between the slices' },
        { word: 'Noodles', hint: 'Long strings of the eastern dough' },
        { word: 'Curry', hint: 'The global dance of the varied spices' },
        { word: 'Soup', hint: 'A warm hug in a bowl' },
        { word: 'Fried Rice', hint: 'Grains tossed in a fiery wok' },
        { word: 'Donut', hint: 'A ring of sugar and hollow center' },
        { word: 'Popcorn', hint: 'The sound of the cinema starts' },
        { word: 'Honey', hint: 'The liquid gold from the flowers' },
        { word: 'Cheese', hint: 'The aged heart of the dairy' },
        { word: 'Bread', hint: 'The simple rise of the flour' },
        { word: 'Fruit', hint: 'The natural sugar of the branch' },
        { word: 'Vegetable', hint: 'The savory gift of the earth' },
        { word: 'Fish', hint: 'The scale of the deep blue' },
        { word: 'Egg', hint: 'The oval start of many dishes' },
        { word: 'Juice', hint: 'The liquid squeeze of the fruit' },
        { word: 'Yogurt', hint: 'The cool fermented white' },
        { word: 'Nuts', hint: 'A hard shell and a crunchy heart' },
        { word: 'Chips', hint: 'A salty crunch from the soil' },
        { word: 'Cookies', hint: 'Small baked bites of the oven' },
        { word: 'Stew', hint: 'Slowly simmered warmth of the pot' }
    ],
    'Places': [
        { word: 'Chennai', hint: 'The city of the long beach and temple bells' },
        { word: 'Madurai', hint: 'Where the jasmine blooms and the goddess rules' },
        { word: 'Ooty', hint: 'The misty crown of the blue hills' },
        { word: 'Paris', hint: 'The iron tower and the city of light' },
        { word: 'London', hint: 'The river Thames and the ticking clock' },
        { word: 'New York', hint: 'The city that never closes its eyes' },
        { word: 'Tokyo', hint: 'Neon lights and the sunrise spirit' },
        { word: 'Dubai', hint: 'A futuristic oasis in the golden sands' },
        { word: 'Singapore', hint: 'The clean garden city of the lion' },
        { word: 'Sydney', hint: 'A white opera house by the harbor' },
        { word: 'Rome', hint: 'The ruins that once ruled the world' },
        { word: 'Berlin', hint: 'A wall that fell and a new history' },
        { word: 'Moscow', hint: 'The colorful domes and the red heart' },
        { word: 'Mumbai', hint: 'The gateway to India and the sea breeze' },
        { word: 'Delhi', hint: 'The red fort and the seat of power' },
        { word: 'Bangalore', hint: 'The silicon garden of the technology' },
        { word: 'Hyderabad', hint: 'Minarets, pearls, and a spicy aroma' },
        { word: 'Kolkata', hint: 'A city of joy and vintage trams' },
        { word: 'Jaipur', hint: 'The pink walls of the desert kingdom' },
        { word: 'Maldives', hint: 'A necklace of blue islands' },
        { word: 'Bali', hint: 'The island of the thousand temples' },
        { word: 'Switzerland', hint: 'The precision of watches and snow' },
        { word: 'Iceland', hint: 'Where the ice speaks to the fire' },
        { word: 'Taj Mahal', hint: 'A white marble dream in Agra' },
        { word: 'Eiffel Tower', hint: 'A lace of iron reaching the sky' },
        { word: 'Colosseum', hint: 'An arena of the ancient echoes' },
        { word: 'Pyramids of Giza', hint: 'The triangles that touch the stars' },
        { word: 'Grand Canyon', hint: 'The deep cut of time in the earth' },
        { word: 'Niagara Falls', hint: 'The thunder of the falling water' },
        { word: 'Mount Everest', hint: 'The peak that breathes the thin air' },
        { word: 'Kodaikanal', hint: 'The princess of the mountain heights' },
        { word: 'Coimbatore', hint: 'The cotton heart of the south' },
        { word: 'Trichy', hint: 'The stone that reaches the sky' },
        { word: 'Salem', hint: 'The mountain of the iron and the fruit' },
        { word: 'Vellore', hint: 'A fort of the moat and the gold' },
        { word: 'Thanjavur', hint: 'The big shadow that never falls' },
        { word: 'Kanyakumari', hint: 'Where three seas meet the end' },
        { word: 'Cairo', hint: 'The ancient gate of the desert' },
        { word: 'Rio de Janeiro', hint: 'The giant statue over the bay' },
        { word: 'Los Angeles', hint: 'The city of the fallen angels and stars' },
        { word: 'Las Vegas', hint: 'The neon gamble in the desert' },
        { word: 'San Francisco', hint: 'The golden gate through the fog' },
        { word: 'Washington DC', hint: 'The white house of the capital' },
        { word: 'Beijing', hint: 'The forbidden walls of the east' },
        { word: 'Seoul', hint: 'The technological soul of the peninsula' },
        { word: 'Bangkok', hint: 'The canals and the golden shrines' },
        { word: 'Amsterdam', hint: 'The city of the bridges and bikes' },
        { word: 'Venice', hint: 'A city that floats on its history' },
        { word: 'Athens', hint: 'The cradle of the democracy' },
        { word: 'Ooty', hint: 'The peak of the blue mountains' }
    ]
};